language: ruby
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up instsallation of html-proofer

sudo: flase # route your build to the container-based infrastructure for a faster build
