# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Journey of a Man
email: ikaikastine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Guitar and gear enthusiast, programmer, tech guy, Jesus follower. These are the
  random thoughts of a man as he journies through wherever life might take him.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ikaikastine.github.io" # the base hostname & protocol for your site
twitter_username: ikaikastine
github_username:  ikaikastine

# Build settings
markdown: kramdown
